version: '3.1'
services:
  sogo:
    #build: .
    image: sogo
    ports:
      - 80:80
    environment:        
      - DB_HOST=db
      - DB_USER=sogo
      - DB_PASS=pass
      - DB_DATABASE=sogo
      - DB_USERPROFILES=mysql://sogo:pass@db:3361/sogo/sogo_user_profile
      - DB_FOLDERINFO=mysql://sogo:pass@db:3361/sogo/sogo_folder_info
      - DB_SESSIONSFOLDER=mysql://sogo:pass@db:3361/sogo/sogo_sessions_folder
      - DB_USERVIEW=mysql://sogo:pass@db:3361/sogo/sogo_view
      - IMAP_SERVER=imaps://mail.alb-tec.de:993
      - SIEVE_SERVER=sieve://mail.alb-tec.de:4190
      - SMTP_SERVER=mail.alb-tec.de
      - MAILDOMAIN=mail.alb-tec.de
      - TITLE=alb-TEC SOGO
      - LANGUAGE=English
      - TIMEZONE=Europe/Berlin
      - SUPERUSERS=christopher.hauser@alb-tec.de
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: sogo
      MYSQL_USER: sogo
      MYSQL_PASSWORD: pass
